ARTIFACT_DIR = "artifacts"
FILE_NAME = "jobs_dataset.csv"
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"

DATA_INGESTION_DIR_NAME = "data_ingestion"
DATA_INGESTION_FEATURE_STORE = "feature_store"
DATA_INGESTION_INGESTED = "ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO = 0.2

DATA_TRANSFORMATION_DIR_NAME = "data_transformation"
DATA_TRANSFORMATION_TRANSFORMED_DATA_DIR = "transformed"
DATA_TRANSFORMATION_TRANSFORMER_MODEL_DIR = "transformer"
DATA_TRANSFORMATION_TRAIN_FILE_NAME = "train.npy"
DATA_TRANSFORMATION_TEST_FILE_NAME = "test.npy"
DATA_TRANSFORMATION_MODEL_NAME = "vectorizer.pkl"
